apiVersion: apps/v1
kind: Deployment
metadata:
  name: storeservice
  labels:
    app: storeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storeservice
  template:
    metadata:
      labels:
        app: storeservice
    spec:
      containers:
        - name: storeservice
          image: "username/storeservice:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
