server:
  port: 8084

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000

spring:
  application:
    name: reviewService

  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: default

  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
      separator: //

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans,loggers,conditions,httptrace,threaddump,zipkin
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
  #    org.springframework.security: DEBUG
#    delivery_system: INFO
#    org.hibernate.type: trace
#    org.springframework.cloud: debug
#    org.springframework.jdbc.core: debug
#    org.hibernate.SQL: debug
#    org.springframework.transaction: TRACE
#    org.hibernate.engine.transaction: TRACE
#    io.zipkin.reporter2: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%thread] [%-40.40logger{39}] [%X{traceId},%X{spanId}] : %m%n"